from __future__ import annotations

"""
audit_v232_runtime_postflop_never_arms.py

PokerVision Solver V2.3.2 — runtime output audit for preflop-only arming.

Purpose:
- Inspect Action_Runtime_Plan_JSON files generated by replay/regression.
- Confirm V22 arming never arms non-preflop runtime plans.
- Confirm no real-click flag is enabled.
"""

import json
from collections import Counter
from pathlib import Path
from typing import Any, Dict


ROOT = Path(r"C:\PokerVision_Solver\Script_Test_PokerVision_All_files\Test_Replay_Output")


def _read_json(path: Path) -> Dict[str, Any] | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return payload if isinstance(payload, dict) else None


def _iter_runtime_plans(root: Path):
    for path in root.rglob("*.json"):
        if "Action_Runtime_Plan_JSON" in set(path.parts):
            yield path


def _street(payload: Dict[str, Any]) -> str:
    ctx = payload.get("decision_context")
    if isinstance(ctx, dict) and ctx.get("street"):
        return str(ctx.get("street")).lower()

    v21 = payload.get("v21_preflop_real_click_preflight_gate")
    if isinstance(v21, dict) and v21.get("street"):
        return str(v21.get("street")).lower()

    return str(payload.get("street") or "unknown").lower()


def audit(root: Path = ROOT) -> Dict[str, Any]:
    counters = Counter()
    errors: list[dict[str, Any]] = []
    examples: list[dict[str, Any]] = []

    for path in _iter_runtime_plans(root):
        payload = _read_json(path)
        if not isinstance(payload, dict):
            counters["runtime_plan_unreadable"] += 1
            continue

        counters["runtime_plan_checked"] += 1

        street = _street(payload)
        counters[f"street_{street}"] += 1

        v22 = payload.get("v22_controlled_real_click_arming_gate")
        if isinstance(v22, dict):
            counters["v22_present"] += 1
            armed = v22.get("armed")
            candidate_real_click = v22.get("candidate_real_click_enabled")
        else:
            counters["v22_missing"] += 1
            armed = False
            candidate_real_click = False

        if armed is True:
            counters["armed_true"] += 1
            if street != "preflop":
                errors.append({
                    "path": str(path),
                    "reason": "non_preflop_runtime_plan_armed_true_forbidden",
                    "street": street,
                })

        if payload.get("real_click_enabled") is True:
            counters["runtime_real_click_enabled_true"] += 1
            errors.append({"path": str(path), "reason": "runtime_real_click_enabled_true_forbidden"})

        if candidate_real_click is True:
            counters["candidate_real_click_enabled_true"] += 1
            errors.append({"path": str(path), "reason": "candidate_real_click_enabled_true_forbidden"})

        if len(examples) < 25:
            examples.append({
                "file": path.name,
                "street": street,
                "action": payload.get("planned_action"),
                "sequence": payload.get("target_sequence"),
                "v22_present": isinstance(v22, dict),
                "armed": armed,
                "runtime_real_click": payload.get("real_click_enabled"),
            })

    ok = (
        counters.get("runtime_plan_checked", 0) > 0
        and counters.get("runtime_real_click_enabled_true", 0) == 0
        and counters.get("candidate_real_click_enabled_true", 0) == 0
        and not errors
    )

    return {
        "schema_version": "v232_runtime_postflop_never_arms_audit_v1",
        "ok": ok,
        "root": str(root),
        "counters": dict(counters),
        "errors": errors,
        "examples": examples,
    }


def main() -> int:
    report = audit()

    print("V2.3.2 RUNTIME POSTFLOP NEVER-ARMS AUDIT")
    print("=" * 100)
    print("ROOT =", report["root"])

    print()
    print("COUNTERS:")
    for key, value in report["counters"].items():
        print(f"  {key}: {value}")

    print()
    print("EXAMPLES:")
    for item in report["examples"]:
        print(
            f"  {item['file']} street={item['street']} action={item['action']} "
            f"seq={item['sequence']} v22={item['v22_present']} armed={item['armed']} "
            f"real_click={item['runtime_real_click']}"
        )

    if report["errors"]:
        print()
        print("ERRORS:")
        for item in report["errors"][:30]:
            print(" ", item)

    print()
    print("[RESULT]", "OK" if report["ok"] else "FAILED", "V2.3.2 runtime postflop never-arms audit")
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
